export enum OrderStatus {
  // Main lifecycle
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  PICKUP_SCHEDULED = 'PICKUP_SCHEDULED',
  PICKUP_ASSIGNED = 'PICKUP_ASSIGNED',
  OUT_FOR_PICKUP = 'OUT_FOR_PICKUP',
  PICKUP_ARRIVED = 'PICKUP_ARRIVED',
  PICKED_UP = 'PICKED_UP',
  RECEIVED_AT_FACILITY = 'RECEIVED_AT_FACILITY',
  SORTING = 'SORTING',
  WASHING = 'WASHING',
  IRONING = 'IRONING',
  PACKING = 'PACKING',
  READY_FOR_DISPATCH = 'READY_FOR_DISPATCH',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERY_ARRIVED = 'DELIVERY_ARRIVED',
  DELIVERED = 'DELIVERED',

  // Exception states
  CANCELLED = 'CANCELLED',
  PICKUP_FAILED = 'PICKUP_FAILED',
  PROCESSING_ISSUE = 'PROCESSING_ISSUE',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
}

export enum ServiceType {
  WASH_FOLD = 'WASH_FOLD',
  DRY_CLEAN = 'DRY_CLEAN',
  IRON_ONLY = 'IRON_ONLY',
}

export enum AssignmentType {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
}
